'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function TermsPage() {
  var router = useRouter();
  var [dark, setDark] = useState(true);

  var serif = "'Instrument Serif', Georgia, serif";
  var sans = "'DM Sans', system-ui, sans-serif";
  var bg = dark ? '#0a0a0c' : '#ffffff';
  var tx = dark ? '#f0eff4' : '#111111';
  var txDim = dark ? '#9896a6' : '#555555';
  var txMut = dark ? '#5f5d6e' : '#888888';
  var bdr = dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.08)';
  var bgCard = dark ? '#111115' : '#f8f8fb';
  var navBg = dark ? 'rgba(10,10,12,0.82)' : 'rgba(255,255,255,0.82)';
  var accentLight = dark ? '#C9A84C' : '#a07830';
  var accent = '#C9A84C';

  var sections = [
    {
      title: 'Guidance Disclaimer',
      content: 'PathForge provides AI-generated academic guidance, course recommendations, and career planning tools for informational and educational purposes only. All content, recommendations, roadmaps, and advice generated by PathForge — including but not limited to course selections, college recommendations, extracurricular suggestions, career paths, test preparation guidance, and interview preparation — are suggestions based on artificial intelligence analysis and should be treated as supplementary guidance, not definitive academic or professional advice.\n\nPathForge is not a licensed academic counselor, college admissions consultant, career advisor, or educational institution. The recommendations provided by PathForge do not constitute professional academic advising, and should not be used as a substitute for consultation with qualified professionals including but not limited to school guidance counselors, academic advisors, college admissions officers, career counselors, or other certified education professionals.\n\nUsers should always consult with their school\'s guidance counselor, academic advisor, or other qualified professionals before making any academic, career, or educational decisions based on information provided by PathForge.'
    },
    {
      title: 'No Guarantee of Outcomes',
      content: 'PathForge makes no representations, warranties, or guarantees — express or implied — regarding the accuracy, completeness, reliability, or suitability of any recommendations, course plans, college suggestions, career projections, salary estimates, admission probabilities, or any other information generated by the platform.\n\nPathForge does not guarantee acceptance to any college or university, placement in any course or program, achievement of any grade point average or test score, employment or career outcomes of any kind, or the accuracy of any data including but not limited to admission rates, tuition costs, salary ranges, or institutional information.\n\nAI-generated content may contain inaccuracies, outdated information, or errors. Course availability, admission requirements, and institutional details change frequently and may not be reflected in PathForge\'s recommendations.'
    },
    {
      title: 'Limitation of Liability',
      content: 'To the fullest extent permitted by applicable law, PathForge, its founders, employees, affiliates, and partners shall not be held liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising from or related to the use of PathForge\'s services, including but not limited to:\n\n• Academic decisions made based on PathForge recommendations\n• Course selections, major choices, or school applications influenced by PathForge content\n• Any perceived negative impact on academic performance, college admissions outcomes, or career trajectory\n• Reliance on any information, data, or recommendations provided by PathForge\n• Inaccuracies in AI-generated content including course names, institutional data, or career information\n\nBy using PathForge, you acknowledge and agree that you bear sole responsibility for all academic and career decisions you make, regardless of any recommendations or information provided by the platform.'
    },
    {
      title: 'Use of AI Technology',
      content: 'PathForge uses artificial intelligence and large language models to generate its content and recommendations. AI technology has inherent limitations and may produce responses that are inaccurate, incomplete, biased, or inappropriate. PathForge does not manually review every piece of AI-generated content before it is displayed to users.\n\nPathForge continuously works to improve the accuracy and quality of its AI-generated content, but cannot guarantee that all information will be error-free at all times.'
    },
    {
      title: 'User Responsibilities',
      content: 'By using PathForge, you agree to:\n\n• Treat all PathForge recommendations as suggestions, not directives\n• Verify all course information, institutional data, and requirements directly with the relevant schools and institutions\n• Consult with qualified academic counselors and advisors before making important educational decisions\n• Not rely solely on PathForge for any academic, career, or educational planning\n• Understand that PathForge is a supplementary tool designed to support — not replace — professional guidance'
    },
    {
      title: 'Subscription and Payments',
      content: 'PathForge offers free and paid subscription tiers. Paid subscriptions are billed on a recurring basis (monthly or annually) as selected at the time of purchase. You may cancel your subscription at any time, and cancellation will take effect at the end of the current billing period.\n\nAll prices are listed in US Dollars (USD). PathForge reserves the right to modify pricing with reasonable notice to existing subscribers. Refund requests within 7 days of initial purchase will be honored on a case-by-case basis.'
    },
    {
      title: 'Privacy and Data',
      content: 'PathForge collects and stores user data including account information, generated roadmaps, and usage data to provide and improve its services. PathForge uses Firebase for authentication and data storage, Stripe for payment processing, and third-party AI APIs for content generation.\n\nPathForge does not sell personal user data to third parties. By using PathForge, you consent to the collection and processing of data as described in this section.'
    },
    {
      title: 'Changes to Terms',
      content: 'PathForge reserves the right to update or modify these Terms of Service at any time. Material changes will be communicated to users through the platform. Continued use of PathForge after changes constitutes acceptance of the updated terms.'
    },
    {
      title: 'Contact',
      content: 'If you have questions about these Terms of Service, please contact us at pathforgeapp@gmail.com'
    },
  ];

  return (
    <div style={{ background: bg, color: tx, fontFamily: sans, minHeight: '100vh', transition: 'background 0.3s, color 0.3s' }}>
      <style>{"@import url('https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&display=swap');"}</style>

      {/* NAV */}
      <nav style={{
        position: 'sticky', top: 0, zIndex: 100,
        padding: '18px 32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: navBg, backdropFilter: 'blur(24px) saturate(1.4)',
        borderBottom: '1px solid ' + bdr, transition: 'background 0.3s',
      }}>
        <div onClick={function() { router.push('/'); }} style={{ fontFamily: serif, fontSize: 24, letterSpacing: -0.5, cursor: 'pointer', color: tx }}>
          Path<span style={{ color: accentLight }}>Forge</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button onClick={function() { setDark(!dark); }} style={{
            width: 36, height: 36, borderRadius: 10, border: '1px solid ' + bdr,
            background: bgCard, color: tx, fontSize: 16, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.3s',
          }}>{dark ? '☀️' : '🌙'}</button>
          <button onClick={function() { router.push('/'); }} style={{
            padding: '10px 26px', borderRadius: 100, border: '1px solid ' + bdr,
            background: 'transparent', color: txDim, fontFamily: sans,
            fontSize: 14, fontWeight: 600, cursor: 'pointer', transition: 'all 0.3s',
          }}>← Back to Home</button>
        </div>
      </nav>

      {/* CONTENT */}
      <div style={{ maxWidth: 740, margin: '0 auto', padding: '60px 24px 100px' }}>
        <div style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 12, textTransform: 'uppercase', letterSpacing: 3, color: accentLight, fontWeight: 600, marginBottom: 16 }}>Legal</div>
          <h1 style={{ fontFamily: serif, fontSize: 'clamp(32px, 5vw, 48px)', lineHeight: 1.1, letterSpacing: -1, margin: '0 0 12px', color: tx }}>Terms of Service</h1>
          <p style={{ color: txMut, fontSize: 14 }}>Last updated: April 11, 2026</p>
        </div>

        {/* Important disclaimer banner */}
        <div style={{ background: accent + '12', border: '1px solid ' + accent + '33', borderRadius: 14, padding: '20px 24px', marginBottom: 40 }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
            <span style={{ fontSize: 22, flexShrink: 0, marginTop: 2 }}>⚠️</span>
            <div>
              <div style={{ color: accent, fontSize: 14, fontWeight: 700, marginBottom: 6 }}>Important Notice</div>
              <p style={{ color: txDim, fontSize: 14, lineHeight: 1.7, margin: 0 }}>PathForge is an AI-powered guidance tool only. All recommendations are suggestions and should not replace professional academic advising. Always consult with your school counselor or academic advisor before making educational decisions.</p>
            </div>
          </div>
        </div>

        {sections.map(function(section, i) {
          return (
            <div key={i} style={{ marginBottom: 36 }}>
              <h2 style={{ fontFamily: serif, fontSize: 22, color: tx, margin: '0 0 12px', letterSpacing: -0.3 }}>{(i + 1) + '. ' + section.title}</h2>
              <div style={{ color: txDim, fontSize: 14, lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>{section.content}</div>
            </div>
          );
        })}
      </div>

      {/* FOOTER */}
      <footer style={{ padding: '40px 24px', borderTop: '1px solid ' + bdr, textAlign: 'center', background: bg, transition: 'background 0.3s' }}>
        <div style={{ display: 'flex', justifyContent: 'center', gap: 24, marginBottom: 16, flexWrap: 'wrap' }}>
          <a href="/terms" style={{ color: txMut, fontSize: 13, textDecoration: 'none' }}>Terms of Service</a>
          <a href="/privacy" style={{ color: txMut, fontSize: 13, textDecoration: 'none' }}>Privacy Policy</a>
          <a href="/pricing" style={{ color: txMut, fontSize: 13, textDecoration: 'none' }}>Pricing</a>
          <a href="/waitlist" style={{ color: txMut, fontSize: 13, textDecoration: 'none' }}>Waitlist</a>
          <a href="/contact" style={{ color: txMut, fontSize: 13, textDecoration: 'none' }}>Contact</a>
        </div>
        <p style={{ fontSize: 13, color: txMut }}>© 2026 PathForge · Built with AI, designed for ambition.</p>
      </footer>
    </div>
  );
}
